language: node_js
dist: bionic
sudo: true
node_js:
  - "10"
notifications:
  email:
    recipients:
      - claude.niederlender@inist.fr
      - jean-joffrey.parentin@inist.fr
      - remy.meja@inist.fr
      - conditordev@gmail.com
    on_success: change
on_failure: always
