language: node_js

sudo: required

addons:
  apt:
    packages:
      - oracle-java8-installer
before_script:
  - sleep 10
node_js:
  - "6"
before_install:
  - jdk_switcher use oraclejdk8
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.0.deb && sudo dpkg -i --force-confnew elasticsearch-5.4.0.deb && sudo service elasticsearch restart
services:
  - elasticsearch
notifications:
  email:
    recipients:
      - claude.niederlender@inist.fr
      - jean-baptiste.genicot@inist.fr
      - conditordev@gmail.com
    on_success: change
on_failure: always
