language: node_js
dist: bionic
sudo: true
before_script:
  - sleep 20
node_js:
  - "10"
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.5.4.deb && sudo dpkg -i --force-confnew elasticsearch-6.5.4.deb && sudo systemctl start elasticsearch.service
  - sudo -E /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu
  - sudo systemctl restart elasticsearch.service
notifications:
  email:
    recipients:
      - claude.niederlender@inist.fr
      - jean-joffrey.parentin@inist.fr
      - remy.meja@inist.fr
      - conditordev@gmail.com
    on_success: change
on_failure: always
